---
- name: Name
  hosts: all
  collections:
   - community.kubernetes.k8s
  tasks:
   - name: Creating Name Space
     k8s:
      name: "{{ ns }}"
      api_version: v1
      kind: Namespace
      state: present
     when: ansible_hostname == "vmaster"
   - name: Creating a POD using Ansible
     k8s:
      api_version: v1
      definition:
       kind: Pod
       metadata:
        name: "{{ pod_name }}"
        namespace: "{{ ns }}"
       spec:
        containers:
         - name: "{{ pod_name }}"
           image: nginx
     when: ansible_hostname == "vmaster"
  environment:
   K8S_AUTH_KUBECONFIG: /home/ansible/.kube/config
